local c = require("colors.palette")
local hl = vim.api.nvim_set_hl
local link = function(group, target)
  vim.api.nvim_set_hl(0, group, { link = target, default = true })
end

vim.o.termguicolors = true

for i = 0, 15 do
  local name = ({ "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
                   "bright_black", "bright_red", "bright_green", "bright_yellow",
                   "bright_blue", "bright_magenta", "bright_cyan", "bright_white" })[i + 1]
  vim.g["terminal_color_" .. i] = c["term_" .. name]
end

-- Editor UI
hl(0, "Normal",       { fg = c.fg, bg = c.bg })
hl(0, "NormalFloat",  { fg = c.fg, bg = c.bg_float })
hl(0, "NormalSB",     { fg = c.fg, bg = c.bg_alt })
hl(0, "EndOfBuffer",  { fg = c.bg })
hl(0, "Cursor",       { fg = c.bg, bg = c.cursor })
hl(0, "CursorLine",   { bg = c.cursorline })
hl(0, "CursorLineNr", { fg = c.fg, bold = true })
hl(0, "LineNr",       { fg = c.line_nr })
hl(0, "SignColumn",   { bg = c.bg })
hl(0, "FoldColumn",   { fg = c.fg_dim, bg = c.bg })
hl(0, "Folded",       { fg = c.fg_dim, bg = c.bg_alt })
hl(0, "ColorColumn",  { bg = c.bg_alt })
hl(0, "Visual",       { bg = c.selection })
hl(0, "VisualNOS",    { bg = c.selection })
hl(0, "MatchParen",   { fg = c.match, bold = true })
hl(0, "Search",       { fg = c.fg, bg = c.search })
hl(0, "IncSearch",    { fg = c.bg, bg = c.match })
hl(0, "CurSearch",    { link = "IncSearch" })

hl(0, "Substitute",   { fg = c.bg, bg = c.search })

hl(0, "Conceal",      { fg = c.fg_dim })
hl(0, "NonText",      { fg = c.fg_dim })
hl(0, "Whitespace",   { fg = c.fg_dim })
hl(0, "SpecialKey",   { fg = c.fg_dim })
hl(0, "Directory",    { fg = c.blue })

-- Messages / Command line
hl(0, "ModeMsg",      { fg = c.fg, bold = true })
hl(0, "MoreMsg",      { fg = c.green })
hl(0, "Question",     { fg = c.yellow })
hl(0, "WarningMsg",   { fg = c.warn })
hl(0, "ErrorMsg",     { fg = c.error, bold = true })

-- Status line & Tabs
hl(0, "StatusLine",      { fg = c.fg, bg = c.bg_alt })
hl(0, "StatusLineNC",    { fg = c.fg_dim, bg = c.bg_alt })
hl(0, "TabLine",         { fg = c.fg_dim, bg = c.bg_alt })
hl(0, "TabLineFill",     { bg = c.bg })
hl(0, "TabLineSel",      { fg = c.fg, bg = c.bg, bold = true })
hl(0, "WinSeparator",    { fg = c.border })
hl(0, "VertSplit",       { link = "WinSeparator" })
hl(0, "WinBar",          { fg = c.fg_dim, bg = c.bg_alt })
hl(0, "WinBarNC",        { fg = c.fg_dim, bg = c.bg })

-- Popup menu
hl(0, "Pmenu",         { fg = c.fg, bg = c.bg_alt })
hl(0, "PmenuSel",      { fg = c.bg, bg = c.blue })
hl(0, "PmenuSbar",     { bg = c.border })
hl(0, "PmenuThumb",    { bg = c.fg_dim })
hl(0, "WildMenu",      { fg = c.bg, bg = c.blue })

-- Quickfix
hl(0, "QuickFixLine",  { bg = c.selection })

-- Title / Float
hl(0, "Title",         { fg = c.blue, bold = true })
hl(0, "FloatBorder",   { fg = c.border, bg = c.bg_float })
hl(0, "FloatTitle",    { fg = c.blue, bg = c.bg_float })

-- Diff
hl(0, "DiffAdd",       { bg = c.diff_add })
hl(0, "DiffChange",    { bg = c.diff_chg })
hl(0, "DiffDelete",    { bg = c.diff_del })
hl(0, "DiffText",      { bg = c.selection })

-- Spelling
hl(0, "SpellBad",      { sp = c.error, undercurl = true })
hl(0, "SpellCap",      { sp = c.warn, undercurl = true })
hl(0, "SpellLocal",    { sp = c.info, undercurl = true })
hl(0, "SpellRare",     { sp = c.magenta, undercurl = true })

-- Standard syntax
hl(0, "Comment",         { fg = c.green, italic = true })
hl(0, "SpecialComment",  { fg = c.green, italic = true })
hl(0, "Constant",        { fg = c.cyan })
hl(0, "String",          { fg = c.fg_dim })
hl(0, "Character",       { fg = c.green })
hl(0, "Number",          { fg = c.cyan })
hl(0, "Boolean",         { fg = c.cyan })
hl(0, "Float",           { fg = c.cyan })
hl(0, "Identifier",      { fg = c.fg })
hl(0, "Function",        { fg = c.blue })
hl(0, "Statement",       { fg = c.red })
hl(0, "Conditional",     { fg = c.red })
hl(0, "Repeat",          { fg = c.red })
hl(0, "Label",           { fg = c.red })
hl(0, "Operator",        { fg = c.magenta })
hl(0, "Keyword",         { fg = c.red })
hl(0, "Exception",       { fg = c.red })
hl(0, "PreProc",         { fg = c.orange })
hl(0, "Include",         { fg = c.blue })
hl(0, "Define",          { fg = c.orange })
hl(0, "Macro",           { fg = c.orange })
hl(0, "PreCondit",       { fg = c.orange })
hl(0, "Type",            { fg = c.yellow })
hl(0, "StorageClass",    { fg = c.orange })
hl(0, "Structure",       { fg = c.orange })
hl(0, "Typedef",         { fg = c.yellow })
hl(0, "Special",         { fg = c.pink })
hl(0, "SpecialChar",     { fg = c.pink })
hl(0, "Tag",             { fg = c.pink })
hl(0, "Delimiter",       { fg = c.fg })
hl(0, "Debug",           { fg = c.pink })
hl(0, "Underlined",      { underline = true })
hl(0, "Ignore",          { fg = c.fg_dim })
hl(0, "Error",           { fg = c.error })
hl(0, "Todo",            { fg = c.bg, bg = c.yellow })

-- Treesitter
hl(0, "@comment",         { link = "Comment" })
hl(0, "@error",           { fg = c.error })
hl(0, "@none",            {})
hl(0, "@preproc",         { link = "PreProc" })
hl(0, "@define",          { link = "Define" })
hl(0, "@operator",        { link = "Operator" })

hl(0, "@punctuation.delimiter", { fg = c.fg })
hl(0, "@punctuation.bracket",   { fg = c.fg })
hl(0, "@punctuation.special",   { fg = c.pink })

hl(0, "@string",                { link = "String" })
hl(0, "@string.escape",         { fg = c.pink })
hl(0, "@string.regex",          { fg = c.cyan })
hl(0, "@string.special",        { fg = c.pink })
hl(0, "@character",             { link = "Character" })
hl(0, "@character.special",     { fg = c.pink })

hl(0, "@boolean",               { link = "Boolean" })
hl(0, "@number",                { link = "Number" })
hl(0, "@float",                 { link = "Float" })

hl(0, "@function",              { link = "Function" })
hl(0, "@function.builtin",      { fg = c.pink })
hl(0, "@function.call",         { fg = c.blue })
hl(0, "@function.macro",        { fg = c.orange })
hl(0, "@method",                { fg = c.blue })
hl(0, "@method.call",           { fg = c.blue })
hl(0, "@constructor",           { fg = c.orange })

hl(0, "@parameter",             { fg = c.tan })
hl(0, "@parameter.reference",   { fg = c.tan })
hl(0, "@field",                 { fg = c.cyan })
hl(0, "@property",              { fg = c.cyan })

hl(0, "@variable",             { fg = c.fg })
hl(0, "@variable.builtin",     { fg = c.pink })
hl(0, "@variable.member",      { fg = c.cyan })
hl(0, "@variable.parameter",   { link = "@parameter" })

hl(0, "@constant",             { link = "Constant" })
hl(0, "@constant.builtin",     { fg = c.cyan, bold = true })
hl(0, "@constant.macro",       { fg = c.orange })

hl(0, "@type",                 { link = "Type" })
hl(0, "@type.builtin",         { fg = c.yellow, bold = true })
hl(0, "@type.definition",      { fg = c.yellow })
hl(0, "@namespace",            { fg = c.orange })
hl(0, "@module",               { fg = c.orange })
hl(0, "@label",                { fg = c.red })

hl(0, "@keyword",              { link = "Keyword" })
hl(0, "@keyword.function",     { fg = c.red })
hl(0, "@keyword.operator",     { fg = c.magenta })
hl(0, "@keyword.return",       { fg = c.red })
hl(0, "@conditional",          { link = "Conditional" })
hl(0, "@repeat",               { link = "Repeat" })
hl(0, "@debug",                { link = "Debug" })
hl(0, "@include",              { link = "Include" })
hl(0, "@exception",            { link = "Exception" })

hl(0, "@tag",                  { fg = c.blue })
hl(0, "@tag.attribute",        { fg = c.cyan })
hl(0, "@tag.delimiter",        { fg = c.fg_dim })

hl(0, "@text",                 { fg = c.fg })
hl(0, "@text.strong",          { bold = true })
hl(0, "@text.emphasis",        { italic = true })
hl(0, "@text.underline",       { underline = true })
hl(0, "@text.strike",          { strikethrough = true })
hl(0, "@text.title",           { fg = c.blue, bold = true })
hl(0, "@text.literal",         { fg = c.green })
hl(0, "@text.uri",             { fg = c.blue, underline = true })
hl(0, "@text.math",            { fg = c.cyan })
hl(0, "@text.environment",     { fg = c.orange })
hl(0, "@text.environment.name",{ fg = c.orange })
hl(0, "@text.note",            { fg = c.bg, bg = c.info, bold = true })
hl(0, "@text.warning",         { fg = c.bg, bg = c.warn, bold = true })
hl(0, "@text.danger",          { fg = c.bg, bg = c.error, bold = true })
hl(0, "@text.diff.add",        { fg = c.green, bg = c.diff_add })
hl(0, "@text.diff.delete",     { fg = c.red, bg = c.diff_del })


-- Diagnostic
hl(0, "DiagnosticHint",          { fg = c.hint })
hl(0, "DiagnosticInfo",          { fg = c.info })
hl(0, "DiagnosticWarn",          { fg = c.warn })
hl(0, "DiagnosticError",         { fg = c.error })
hl(0, "DiagnosticOk",            { fg = c.green })
hl(0, "DiagnosticUnnecessary",   { fg = c.fg_dim })

hl(0, "DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = c.warn, undercurl = true })
hl(0, "DiagnosticUnderlineError",{ sp = c.error, undercurl = true })
hl(0, "DiagnosticUnderlineOk",   { sp = c.green, undercurl = true })

hl(0, "DiagnosticVirtualTextHint", { fg = c.hint })
hl(0, "DiagnosticVirtualTextInfo", { fg = c.info })
hl(0, "DiagnosticVirtualTextWarn", { fg = c.warn })
hl(0, "DiagnosticVirtualTextError",{ fg = c.error })
hl(0, "DiagnosticSignHint",        { fg = c.hint })
hl(0, "DiagnosticSignInfo",        { fg = c.info })
hl(0, "DiagnosticSignWarn",        { fg = c.warn })
hl(0, "DiagnosticSignError",       { fg = c.error })
hl(0, "DiagnosticFloatingHint",    { fg = c.hint })
hl(0, "DiagnosticFloatingInfo",    { fg = c.info })
hl(0, "DiagnosticFloatingWarn",    { fg = c.warn })
hl(0, "DiagnosticFloatingError",   { fg = c.error })

-- LSP
hl(0, "LspReferenceText",       { bg = c.selection })
hl(0, "LspReferenceRead",       { bg = c.selection })
hl(0, "LspReferenceWrite",      { bg = c.selection })
hl(0, "LspInlayHint",           { fg = c.fg_dim, bg = c.bg_alt })
hl(0, "LspSignatureActiveParameter", { fg = c.orange, bold = true })
hl(0, "LspCodeLens",            { fg = c.fg_dim })
hl(0, "LspCodeLensSeparator",   { fg = c.fg_dim })

-- Telescope
hl(0, "TelescopeNormal",             { fg = c.fg, bg = c.bg_float })
hl(0, "TelescopeBorder",             { fg = c.border, bg = c.bg_float })
hl(0, "TelescopeTitle",              { fg = c.blue, bg = c.bg_float })
hl(0, "TelescopePromptNormal",       { fg = c.fg, bg = c.bg_alt })
hl(0, "TelescopePromptBorder",       { fg = c.border, bg = c.bg_alt })
hl(0, "TelescopePromptTitle",        { fg = c.bg, bg = c.blue })
hl(0, "TelescopeResultsNormal",      { fg = c.fg, bg = c.bg_float })
hl(0, "TelescopeResultsBorder",      { fg = c.border, bg = c.bg_float })
hl(0, "TelescopeResultsTitle",       { fg = c.blue, bg = c.bg_float })
hl(0, "TelescopePreviewNormal",      { fg = c.fg, bg = c.bg_float })
hl(0, "TelescopePreviewBorder",      { fg = c.border, bg = c.bg_float })
hl(0, "TelescopePreviewTitle",       { fg = c.green, bg = c.bg_float })
hl(0, "TelescopeSelection",          { fg = c.fg, bg = c.selection })
hl(0, "TelescopeSelectionCaret",     { fg = c.red })
hl(0, "TelescopeMultiSelection",     { fg = c.orange })
hl(0, "TelescopeMatching",           { fg = c.blue })
hl(0, "TelescopePromptPrefix",       { fg = c.red })

-- WhichKey
hl(0, "WhichKey",          { fg = c.magenta })
hl(0, "WhichKeyGroup",     { fg = c.blue })
hl(0, "WhichKeyDesc",      { fg = c.fg })
hl(0, "WhichKeySeparator", { fg = c.fg_dim })
hl(0, "WhichKeyBorder",    { fg = c.border })
hl(0, "WhichKeyFloat",     { bg = c.bg_float })
hl(0, "WhichKeyValue",     { fg = c.green })

-- Oil
hl(0, "OilFile",    { fg = c.fg })
hl(0, "OilDir",     { fg = c.blue })
hl(0, "OilLink",    { fg = c.cyan })
hl(0, "OilSpecial", { fg = c.pink })

-- Blink (completion menu)
hl(0, "BlinkCmpMenu",               { fg = c.fg, bg = c.bg_alt })
hl(0, "BlinkCmpMenuBorder",         { fg = c.border })
hl(0, "BlinkCmpScrollBarThumb",     { bg = c.fg_dim })
hl(0, "BlinkCmpScrollBarGutter",    { bg = c.bg_alt })
hl(0, "BlinkCmpDoc",                { fg = c.fg, bg = c.bg_float })
hl(0, "BlinkCmpDocBorder",          { fg = c.border })
hl(0, "BlinkCmpLabel",              { fg = c.fg })
hl(0, "BlinkCmpLabelMatch",         { fg = c.blue, bold = true })
hl(0, "BlinkCmpLabelDescription",   { fg = c.fg_dim })
hl(0, "BlinkCmpSource",             { fg = c.fg_dim })

hl(0, "BlinkCmpKindKeyword",        { fg = c.red })
hl(0, "BlinkCmpKindVariable",       { fg = c.fg })
hl(0, "BlinkCmpKindConstant",       { fg = c.cyan })
hl(0, "BlinkCmpKindFunction",       { fg = c.blue })
hl(0, "BlinkCmpKindMethod",         { fg = c.blue })
hl(0, "BlinkCmpKindConstructor",    { fg = c.orange })
hl(0, "BlinkCmpKindProperty",       { fg = c.cyan })
hl(0, "BlinkCmpKindField",          { fg = c.cyan })
hl(0, "BlinkCmpKindClass",          { fg = c.yellow })
hl(0, "BlinkCmpKindInterface",      { fg = c.yellow })
hl(0, "BlinkCmpKindStruct",         { fg = c.yellow })
hl(0, "BlinkCmpKindEnum",           { fg = c.yellow })
hl(0, "BlinkCmpKindEnumMember",     { fg = c.cyan })
hl(0, "BlinkCmpKindEvent",          { fg = c.pink })
hl(0, "BlinkCmpKindOperator",       { fg = c.magenta })
hl(0, "BlinkCmpKindTypeParameter",  { fg = c.yellow })
hl(0, "BlinkCmpKindModule",         { fg = c.orange })
hl(0, "BlinkCmpKindFile",           { fg = c.fg })
hl(0, "BlinkCmpKindFolder",         { fg = c.blue })
hl(0, "BlinkCmpKindUnit",           { fg = c.fg })
hl(0, "BlinkCmpKindSnippet",        { fg = c.magenta })
hl(0, "BlinkCmpKindText",           { fg = c.fg })
hl(0, "BlinkCmpKindReference",      { fg = c.fg })
hl(0, "BlinkCmpKindColor",          { fg = c.pink })

-- Gitsigns
hl(0, "GitSignsAdd",         { fg = c.green, bg = c.bg })
hl(0, "GitSignsChange",      { fg = c.orange, bg = c.bg })
hl(0, "GitSignsDelete",      { fg = c.red, bg = c.bg })
hl(0, "GitSignsAddLn",       { bg = c.diff_add })
hl(0, "GitSignsChangeLn",    { bg = c.diff_chg })
hl(0, "GitSignsDeleteLn",    { bg = c.diff_del })
hl(0, "GitSignsAddNr",       { fg = c.green })
hl(0, "GitSignsChangeNr",    { fg = c.orange })
hl(0, "GitSignsDeleteNr",    { fg = c.red })
hl(0, "GitSignsStagedAdd",   { fg = c.green })
hl(0, "GitSignsStagedChange",{ fg = c.orange })
hl(0, "GitSignsStagedDelete",{ fg = c.red })

-- Fugitive
hl(0, "FugitiveHeading",     { fg = c.blue, bold = true })
hl(0, "FugitiveHash",        { fg = c.cyan })
