-- return {
--     "supermaven-inc/supermaven-nvim",
--     config = function()
--         require("supermaven-nvim").setup({
--             ignore_filetypes = { "oil" },
--             disable_inline_completion = true,
--             disable_keymaps = true,
--         })
--     end
-- }
return {}
